### ISSUE TITLE
Fuzzy clustering based pseudo-swept volume decomposition for hexahedral meshing

### ISSUE THREAD

**Issue by xiaoyan16a** [cnr-isti-vclab/HexaLab#17]
DOI: https://doi.org/10.1016/j.cad.2017.10.001

**Comment by xiaoyan16a** [comment]
Link to the dataset: https://drive.google.com/open?id=1BF-FUwJokJ7c4Cga0y2yZ2QNFEgXbXtb

**Comment by mlivesu** [comment]
Thank you for sharing your data with us. I just sent a pull request to Paolo.

Please be aware that the 4th mesh was discarded because it contains degenerate elements. In particular, there is a fake-hexahedron containing the same vertex (id 148) twice. This is the corresponding line in the input file:

8 16238 16237 69146 69145 148 148 16128 16127

Hexalab does not support such ill-defined elements. Vertices may be geometrically coincident, but are required to be at least topologically distinct.

**Comment by cignoni** [comment]
Pull request merged, Thanks!
